spring:
  application:
    name: krzpro
  main:
    banner-mode:
  profiles:
    active: ${APP_ENV:dev}

server:
  port: 8080

my:
  custom:
    login-url: test-login
    credentials:
      user: test-user
      password: pass

app:
  myProperty: false
  environment: ${APP_ENV:dev}

logging:
  level:
    root: off

