spring:
  application:
    name: krzpro
  main:
    banner-mode: off
  profiles:
    active: dev

server:
  port: 8081

my:
  custom:
    login-url: test-login
    credentials:
      user: test-user
      password: pass

app:
  myProperty: false
  environment: qa

logging:
  level:
    root: off


